
name: Lighthouse Audit (Live Site)
on:
  workflow_dispatch:
jobs:
  audit-live-site:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: foo-software/lighthouse-check-action@v12.0.1
      with:
        urls: 'https://lewis.cowles.uk/'
        outputDirectory: /tmp/lighthouse-report
    - name: Upload results as an artifact
      uses: actions/upload-artifact@main
      with:
        name: lighthouse-report
        path: /tmp/lighthouse-report
