name: Lighthouse Audit
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: foo-software/lighthouse-check-action@v12.0.1
      with:
        urls: 'https://lewiscowles1986.github.io/'
        outputDirectory: ${{ github.workspace }}/reports/lighthouse-report
    - name: Upload results as an artifact
      uses: actions/upload-artifact@main
      with:
        name: lighthouse-report
        path: ${{ github.workspace }}/reports/lighthouse-report