
name: Lighthouse Audit (Live Site)
on:
  workflow_dispatch:
jobs:
  audit-live-site:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@a3bcc9973b3ce65beff316b3cac53b92e58dcc12
      with:
        url: 'https://www.lewiscowles.co.uk/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@main
      with:
        name: report
        path: './report'
