name: Lighthouse Audit
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@a3bcc9973b3ce65beff316b3cac53b92e58dcc12
      with:
        url: 'https://lewiscowles1986.github.io/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@main
      with:
        name: report
        path: './report'
